[versions]
agp = "8.9.2"
appcompat = "1.7.0"
desugar_jdk_libs = "2.1.5"
flexbox = "3.0.0"
gson = "2.11.0"
leakcanaryAndroid = "2.14"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
navigationFragment = "2.9.0"
navigationSafeArgsGradlePlugin = "2.9.1"
navigationUi = "2.9.0"
pagingRuntimeVersion = "3.3.6"
roomRuntime = "2.7.1"
viewbinding = "8.10.1"
playServicesBasement = "18.7.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntimeVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-paging = { module = "androidx.room:room-paging", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
viewbinding = { group = "androidx.databinding", name = "viewbinding", version.ref = "viewbinding" }
play-services-basement = { group = "com.google.android.gms", name = "play-services-basement", version.ref = "playServicesBasement" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

